name: Run tests on all postgres versions

on: push

jobs:
  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Run test script
        uses: actions/checkout@v2        
        run: |
          ./test.sh
