name: Postgres tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          ./test.sh 14
        env:
          PGPASSWORD: postgres
